import { useRef, forwardRef } from "react";
import { useReactToPrint } from "react-to-print";
import Html2Pdf from "js-html2pdf";

export default function App() {
  const componentRef = useRef();
  const handlePrint = useReactToPrint({
    content: () => componentRef.current,
    onPrintError: (error) => console.log(error),
    print: async (printIframe) => {
      const document = printIframe.contentDocument;
      if (document) {
        const ticketElement = document.getElementsByClassName("ticket")[0];
        ticketElement.style.display = "block";
        const options = {
          margin: 0,
          filename: "ticket.pdf",
          jsPDF: { unit: "mm", format: "a4", orientation: "portrait" },
        };
        try {
          // Assume Html2Pdf is already defined and ticketElement.current is valid
          const exporter = new Html2Pdf(ticketElement, options);
          const stringData = await exporter.getDataUri();

          // Strip the MIME type prefix if present
          const base64String = stringData.split(",")[1];

          // Decode base64 string
          const binaryString = atob(base64String);
          const len = binaryString.length;
          const bytes = new Uint8Array(len);
          for (let i = 0; i < len; i++) {
            bytes[i] = binaryString.charCodeAt(i);
          }
          const binaryData = bytes.buffer;

          // Create a blob and URL
          const blob = new Blob([binaryData], { type: "application/pdf" });
          const url = URL.createObjectURL(blob);
          console.log(url);
          const anchor = document.createElement("a");
          anchor.href = url;
          anchor.download = "quotation";
          document.body.appendChild(anchor);
          anchor.click();
          document.body.removeChild(anchor);
        } catch (e) {
          console.log(e);
        }
      }
    },
  });
  return (
    <div>
      <button onClick={handlePrint}>Print sample ticket</button>
      <TicketSample ref={componentRef} />
    </div>
  );
}

const TicketSample = forwardRef((props, ref) => {
  return (
    <div className={"ticket"} ref={ref}>
      <div className={"ticket-header"}>
        <h2>Ticket of the day</h2>
      </div>
      <div className={"details"}>
        <p>
          <strong>Date:</strong> June 6th, 2024
        </p>
        <p>
          <strong>Address:</strong> Newtown
        </p>
        <p>
          <strong>Item:</strong> A smart device
        </p>
        <p>
          <strong>Price:</strong> $500
        </p>
      </div>
      <p>
        In the grand game of acquiring a new abode, the age-old debate between
        buying an existing house and building a brand-new one continues to
        captivate prospective homeowners. Both options have their merits, but
        let's take a lighthearted stroll through the perks of opting for a
        pre-built dwelling.
      </p>
      <p>
        Then there's the joy of exploring neighborhoods with character and
        history. Buying a house often means settling into an established
        community, complete with charming local spots and friendly neighbors.
        Sure, you might not have personally picked out every detail of your
        home, but there's a unique charm in discovering the stories embedded in
        its walls and the quirks that come with a house that's been lived in.
      </p>
      <p>
        In the end, whether you're swiping right on a charming existing home or
        swaying to the rhythm of your own construction symphony, the decision
        between buying and building is a personal one. But hey, there's
        something undeniably delightful about stepping into a house and
        immediately feeling at home – no hard hat required.
      </p>
      <p className="lower">Article generated by ChatGPT</p>
    </div>
  );
});
